import { Router, type IRouter } from "express";
import healthRouter from "./health";
import ordersRouter from "./orders";
import driversRouter from "./drivers";
import lineRouter from "./line";
import customersRouter from "./customers";
import vehicleTypesRouter from "./vehicleTypes";
import licensesRouter from "./licenses";
import enterpriseRouter from "./enterprise";
import outsourcingRouter from "./outsourcing";
import { pricingRouter } from "./pricing";
import paymentsRouter from "./payments";
import permissionsRouter from "./permissions";
import aiChatRouter from "./aiChat";
import authRouter from "./auth";
import { routePricesRouter } from "./routePrices";
import { vehicleCostsRouter } from "./vehicleCosts";
import { smartOrderRouter } from "./smartOrder";
import { driverOnboardingRouter } from "./driverOnboarding";
import { customerManagementRouter } from "./customerManagement";
import { ratingsRouter } from "./ratings";
import { customerNotificationsRouter } from "./customerNotifications";
import { systemConfigRouter } from "./systemConfig";
import { invoicesRouter } from "./invoices";
import { biddingRouter } from "./bidding";
import { driverIncomeRouter } from "./driverIncome";
import { fleetRegistrationRouter } from "./fleetRegistration";
import { paymentMethodsRouter } from "./paymentMethods";
import { performanceRouter } from "./performance";
import { quickOrderRouter } from "./quickOrder";
import { dispatchAlertsRouter } from "./dispatchAlerts";
import { kpiDashboardRouter } from "./kpiDashboard";
import { auditMiddleware } from "../middleware/audit";

const router: IRouter = Router();

router.use(auditMiddleware);

router.use(healthRouter);
router.use(ordersRouter);
router.use(driversRouter);
router.use(lineRouter);
router.use(customersRouter);
router.use(vehicleTypesRouter);
router.use(licensesRouter);
router.use(enterpriseRouter);
router.use(outsourcingRouter);
router.use("/orders", pricingRouter);
router.use(paymentsRouter);
router.use(permissionsRouter);
router.use(aiChatRouter);
router.use(authRouter);
router.use(routePricesRouter);
router.use(vehicleCostsRouter);
router.use(smartOrderRouter);
router.use(driverOnboardingRouter);
router.use(customerManagementRouter);
router.use("/ratings", ratingsRouter);
router.use("/customer-notifications", customerNotificationsRouter);
router.use("/system-config", systemConfigRouter);
router.use(invoicesRouter);
router.use(biddingRouter);
router.use(driverIncomeRouter);
router.use(fleetRegistrationRouter);
router.use(paymentMethodsRouter);
router.use(performanceRouter);
router.use("/quick-order", quickOrderRouter);
router.use(dispatchAlertsRouter);
router.use(kpiDashboardRouter);

export default router;
