import { Router, type IRouter } from "express";
import healthRouter from "./health";
import ordersRouter from "./orders";
import driversRouter from "./drivers";
import lineRouter from "./line";
import customersRouter from "./customers";
import vehicleTypesRouter from "./vehicleTypes";
import licensesRouter from "./licenses";
import enterpriseRouter from "./enterprise";
import outsourcingRouter from "./outsourcing";
import { pricingRouter } from "./pricing";
import paymentsRouter from "./payments";
import permissionsRouter from "./permissions";
import aiChatRouter from "./aiChat";
import authRouter from "./auth";
import { routePricesRouter } from "./routePrices";
import { vehicleCostsRouter } from "./vehicleCosts";
import { smartOrderRouter } from "./smartOrder";
import { driverOnboardingRouter } from "./driverOnboarding";
import { customerManagementRouter } from "./customerManagement";
import { ratingsRouter } from "./ratings";
import { customerNotificationsRouter } from "./customerNotifications";
import { systemConfigRouter } from "./systemConfig";
import { invoicesRouter } from "./invoices";
import { biddingRouter } from "./bidding";
import { driverIncomeRouter } from "./driverIncome";
import { fleetRegistrationRouter } from "./fleetRegistration";
import { paymentMethodsRouter } from "./paymentMethods";
import { performanceRouter } from "./performance";
import { quickOrderRouter } from "./quickOrder";
import { dispatchAlertsRouter } from "./dispatchAlerts";
import { kpiDashboardRouter } from "./kpiDashboard";
import { approvalsRouter } from "./approvals";
import { costEventsRouter } from "./costEvents";
import { auditLogRouter } from "./auditLog";
import { costAnalysisRouter } from "./costAnalysis";
import { settlementExportRouter } from "./settlementExport";
import { orderStatusFlowRouter } from "./orderStatusFlow";
import { dispatchSuggestRouter } from "./dispatchSuggest";
import { zonesRouter } from "./zones";
import { dailyOpsRouter } from "./dailyOps";
import { orderImportRouter } from "./orderImport";
import { routeImportRouter } from "./routeImport";
import { formImportRouter } from "./formImport";
import { autoRoutingRouter } from "./autoRouting";
import { zonePermissionsRouter } from "../middleware/zoneScope";
import { presenceRouter } from "./presence";
import { auditMiddleware } from "../middleware/audit";
import { quotesRouter } from "./quotes";
import { franchiseesRouter } from "./franchisees";
import { cashFlowRouter } from "./cashFlow";
import { apiKeysRouter } from "./apiKeys";
import { webhooksRouter } from "./webhooks";
import { openApiRouter } from "./openApi";
import { arLedgerRouter } from "./arLedger";
import { monthlyBillingRouter } from "./monthlyBilling";
import { ecpayWebhookRouter } from "./ecpayWebhook";
import { reportsRouter } from "./reports";
import { sheetSyncRouter } from "./sheetSync";
import { penaltiesRouter } from "./penalties";
import { shopeeRatesRouter } from "./shopeeRates";
import { driverEarningsRouter } from "./driverEarnings";
import { pnlRouter } from "./pnl";
import { fusingaoRouter } from "./fusingao";
import { penaltySyncRouter } from "./penaltySync";
import { rateSyncRouter } from "./rateSync";
import { shopeeDriversRouter } from "./shopeeDrivers";
import { dispatchOrdersRouter } from "./dispatchOrders";
import { shopeeBillingRouter } from "./shopeeBillingImport";
import { fusingaoScheduleRouter } from "./fusingaoScheduleImport";
import { fusingaoBillingDetailRouter } from "./fusingaoBillingDetailImport";
import { fusingaoSheetSyncRouter } from "./fusingaoSheetSync";
import { platformFleetsRouter } from "./platformFleets";
import { fleetOwnerRouter } from "./fleetOwner";
import { fleetDriverRouter } from "./fleetDriver";
import { requireFleetOwner, requireFleetDriver } from "../middleware/fleetAuth";
import { commissionManagementRouter } from "./commissionManagement";

const router: IRouter = Router();

router.use(auditMiddleware);

router.use(healthRouter);
router.use(orderImportRouter);
router.use(routeImportRouter);
router.use(formImportRouter);
router.use(ordersRouter);
router.use(driversRouter);
router.use(lineRouter);
router.use(customersRouter);
router.use(vehicleTypesRouter);
router.use(licensesRouter);
router.use(enterpriseRouter);
router.use(outsourcingRouter);
router.use("/orders", pricingRouter);
router.use(paymentsRouter);
router.use(permissionsRouter);
router.use(aiChatRouter);
router.use(authRouter);
router.use(routePricesRouter);
router.use(vehicleCostsRouter);
router.use(smartOrderRouter);
router.use(driverOnboardingRouter);
router.use(customerManagementRouter);
router.use("/ratings", ratingsRouter);
router.use("/customer-notifications", customerNotificationsRouter);
router.use("/system-config", systemConfigRouter);
router.use(invoicesRouter);
router.use(biddingRouter);
router.use(driverIncomeRouter);
router.use(fleetRegistrationRouter);
router.use(paymentMethodsRouter);
router.use(performanceRouter);
router.use("/quick-order", quickOrderRouter);
router.use(dispatchAlertsRouter);
router.use(kpiDashboardRouter);
router.use(approvalsRouter);
router.use(costEventsRouter);
router.use(auditLogRouter);
router.use(costAnalysisRouter);
router.use(settlementExportRouter);
router.use(orderStatusFlowRouter);
router.use(dispatchSuggestRouter);
router.use(zonesRouter);
router.use(dailyOpsRouter);
router.use(autoRoutingRouter);
router.use(zonePermissionsRouter);
router.use(presenceRouter);
router.use(quotesRouter);
router.use(franchiseesRouter);
router.use(cashFlowRouter);
router.use(apiKeysRouter);
router.use(webhooksRouter);
router.use(openApiRouter);
router.use(arLedgerRouter);
router.use(monthlyBillingRouter);
router.use(ecpayWebhookRouter);
router.use(reportsRouter);
router.use(sheetSyncRouter);
router.use("/penalties", penaltiesRouter);
router.use("/shopee-rates", shopeeRatesRouter);
router.use("/driver-earnings", driverEarningsRouter);
router.use("/pnl", pnlRouter);
router.use("/fusingao", fusingaoRouter);
router.use(penaltySyncRouter);
router.use(rateSyncRouter);
router.use(shopeeDriversRouter);
router.use("/dispatch-orders", dispatchOrdersRouter);
router.use(shopeeBillingRouter);
router.use("/fusingao", fusingaoScheduleRouter);
router.use("/fusingao", fusingaoBillingDetailRouter);
router.use("/fusingao", fusingaoSheetSyncRouter);

// ── 富詠加盟車行管理平台 ──────────────────────────────────────────────────────
router.use(platformFleetsRouter);                        // 平台管理端：/platform/fleets
router.use("/fleet", requireFleetOwner, fleetOwnerRouter);   // 車行老闆（/fleet/* 才套 auth）
router.use("/driver", requireFleetDriver, fleetDriverRouter); // 司機手機端（/driver/* 才套 auth）
router.use(commissionManagementRouter);                       // 抽成管理

export default router;
